qsort: use rand() not random()
random(3) is marked deprecated and requires the _BSD_SOURCE feature.
Use rand(3) instead of which is an alias of random(3).  With old code,
build failed with:

| lib/qsort.c: In function 'quicksort':
| lib/qsort.c:33:3: error: implicit declaration of function 'random' [-Werror=implicit-function-declaration]
| cc1: some warnings being treated as errors

Signed-off-by: Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>